### ISSUE TITLE
jujucharms.com query: can't find spark charm

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#1]
Using jujucharms.com solution search field for "spark" does not return any results for the spark charm. However, when I use manage.jujucharms.com I find the result I am looking for.

-thanks,
Antonio

**Comment by arosales** [comment]
# Comment from Rick Harding (rharding)

There are two known bugs with the code loading charms into jujucharms.com currently. One is fixed in the 4.0.0 release that we're working with IS to get out. The other a fix is landed and will be in a 4.0.1 release at the start of next week.

We'll test this out in QA and verify that the spark charm does appear.

I'm closing this bug as invalid here as it's not a juju-gui bug. Please report bugs for jujucharms.com at https://github.com/CanonicalLtd/jujucharms.com/issues

If you would like I can file this over there but then you'll lose notifications and such as we follow up. Just let me know which way you prefer.

**Comment by mitechie** [comment]
Another related ingestion bug that is part of the releases. Adding it here so that we track that with a release of 4.0.1 that these are both fixed.

```
When using jujucharms.com some charms are duplicated

https://jujucharms.com/q/mysql

There are several entries that are actually the same, because it points to the same URL
```

**Comment by urosj** [comment]
@arosales, here are results with 4.0.1 code. Is the issue solved, anything still missing?

{"Id":"cs:~asanjar/trusty/spark-7"},{"Id":"cs:~bigdata-dev/trusty/spark-0"},{"Id":"cs:~jorge/bundle/spark-cluster-1"},{"Id":"cs:~jorge/bundle/spark-cluster-trunk-1"}

**Comment by mitechie** [comment]
Thanks for verifying @urosj . We just need to get 4.0.1 out the door.

**Comment by mitechie** [comment]
Another one to make sure we catch after release https://staging.jujucharms.com/hadoop/trusty/16

**Comment by urosj** [comment]
@arosales With new release, here we go: https://jujucharms.com/u/asanjar/spark/trusty/7
Also https://jujucharms.com/q/spark
