### ISSUE TITLE
Search field has inconsistent width

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#537]
1\. Go to the [Jaas](https://jujucharms.com/jaas) or [Kubernetes](https://jujucharms.com/kubernetes) page and look at the search field.
2\. Go to the [Openstack](https://jujucharms.com/openstack) or [big data](https://jujucharms.com/big-data) page and look at the search field.

What you see:

1\. The search field is wide.
![jujucharms com search field wide](https://user-images.githubusercontent.com/19801137/43449119-90243d4c-94a7-11e8-897e-1dae02338814.png)

2\. The search field is narrow.
![jujucharms com search field narrow](https://user-images.githubusercontent.com/19801137/43449115-8bcc8074-94a7-11e8-9ba5-a50bd3ae3191.png)

What you should see: The search field is a consistent width across pages.

**Comment by frankban** [comment]
Good catch! Thanks for reporting.

**Comment by barrymcgee** [comment]
Fixed by https://github.com/CanonicalLtd/blues_browser/pull/1826

**Comment by matthewpaulthomas** [comment]
How often is jujucharms.com released? This was closed 8 days ago, but I still see the bug exactly as reported.

**Comment by hatched** [comment]
@matthewpaulthomas this fix has gone out to production, maybe your cache hasn't updated?

**Comment by hatched** [comment]
@matthewpaulthomas sorry it looks like the issue only shows in Firefox and the release with this fix should be rolled out by the end of the day.

**Comment by barrymcgee** [comment]
@matthewpaulthomas These fixes are now live. 💥
